
name: TestVM

on: pull_request

jobs:
  TestVM:  

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Install dot
      run: |
        sudo apt-get update &&
        sudo apt-get install graphviz

    - name: Run tests
      run: |
        mkdir build &&
        cd build &&
        cmake .. -DENABLE_TESTS=ON &&
        make run_vm_test  
         